kind: pipeline
name: default
workspace:
    base: /go
    path: src/github.com/fanux/LVScare

steps:
- name: build
  image: golang:1.12.1
  commands:
      - go build -o lvscare

- name: publish
  image: plugins/github-release
  settings:
    api_key: 
        from_secret: git-release-token
    files: lvscare
    title: ${DRONE_TAG}
    note: Note.md
    when:
        event: tag

